### ISSUE TITLE
Pass Parameter to function or passing array

### ISSUE THREAD

**Issue by wolf2046ws** [Aniel/FantasticBeasts#9]
This is example how Queries will work 

This function accept 4 parameter ::
1. $db -> to connect to Databse.
2. Second parameter the table name .
3. Third Parameter the Column name .
4. The value

Ex1 : getByField($db, "customers", "id", 1);

Result: 

[0] => Array
        (
            [id] => 1
            [firstname] => Mohammad
            [lastname] => Abdulkarim
            [email] => wolf2046ws@gmaio.com
            [reg_date] => 2018-04-12 09:29:20
        )

Is that right  for front-end or you will pass array with field to functions ?

**Comment by Aniel** [comment]
The right way would be:

```php
$customer = $db->getCustomerById(1);
/*Result
array (
[FirstName] => "Niels",
[LastName] => "Morf",
...
)
*/
```

I dont want to know databse details like `table`, `field`, etc. please abstract it away.

Other example functions are:

```php
$db->createCustomer("Niels", "Morf" ....);
$db->UpdateCustomer(1,  data);
$db->DeleteCustomer(1);
```

**Comment by wolf2046ws** [comment]
Thats what i want to know Thanks .
